config/routes.rb
Task5::Application.routes.draw do
  get "sign_up" => "users#new", :as => "sign_up"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy"
  get "download/all" => "articles#download_article", defaults: {format: :xlsx}
  get "articles/:article/download" => "articles#download_article", defaults: {format: :xlsx}
  resources :users
  resources :sessions
  resources :articles do
    collection { post :import }
  end
  resources :comments
  root "articles#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ruby on Rails Blog</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link href="/assets/css/bootstrap.min.css" rel="stylesheet"> -->
	<!-- <link href="/assets/css/clean-blog.min.css" rel="stylesheet"> -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
	<%= yield(:css) %>
</head>
<body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">RoR Blog</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "Home", "/" %>
                    </li>
                    <% if current_user %>
                    <li>
                        <%= link_to "Add new post", :controller => "articles", :action => "new" %>
                    </li>
                    <li>
                        <%= link_to "welcome #{current_user.username}, Logout", session_path(current_user.id), method: "DELETE" %>
                    </li>
                    <% else %>
                    <li>
                        <%= link_to "Login", login_path %>
                    </li>
                    <li>
                        <%= link_to "Sign Up", sign_up_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-register'} %>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <!-- <header class="intro-header" style="background-image: url('/assets/home-bg.jpg')"> -->
    <header class="intro-header" style="background-image: url('<%= asset_path("home-bg.jpg") %>')">
    <!-- <header class="intro-header" style="background-image: url(<%= asset_url('home-bg') %>)"> -->
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <% if params[:action].eql? "index" or params[:action].eql? "new"%>
                    <div class="site-heading">
                        <h1>RoR Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Blog built with Ruby on Rails</span>
                    </div>
                    <% else %>
                    <div class="post-heading">
                    	<h1><%= yield(:article_title) %></h1>
                        <span class="meta">Posted by <a href="#">Admin</a> on <%= yield(:article_date) %></span>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </header>

    <div class="modal fade" id="modal-register">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Sign up</h4>
                </div>
                <div class="modal-body" id="form-renderer">

                </div>
                <div class="modal-footer" id="form-footer">
                    
                </div>
            </div>
        </div>
    </div>

	<%= yield %>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/sukorenomw">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://facebook.com/sukorenomw">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/sukorenomw">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; YRoR Blog 2015</p>
                </div>
            </div>
        </div>
    </footer>

	<!-- jQuery -->
    <!-- // <script src="/assets/js/jquery.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
    <!-- // <script src="/assets/js/bootstrap.min.js"></script> -->

    <!-- Custom Theme JavaScript -->
    <!-- // <script src="/assets/js/clean-blog.js"></script> -->
    <%= yield(:script) %>
</body>
</html>